import {basename, dirname} from 'path';

import Module from './Module';

import {merge} from './utility';

const Array_proto = Array.prototype;


/**
 * Package to be bundled
 */
export default  class Package {
    /**
     * @param {string}  path         - The entry file path of this package
     *                                 (relative to `process.cwd()`)
     * @param {boolean} [includeAll=false] - Include NPM modules in the final bundle
     * @param {Object}  [moduleMap={}]     - Map to replace some dependencies to others
     * @param {boolean} [noLog=false]      - Disable log output
     */
    constructor(path,  includeAll = false,  moduleMap = { },  noLog = false) {
        /**
         * Module name of this bundled package
         *
         * @type {string}
         */
        this.name = basename( path );

        /**
         * The root path of this package (relative to `process.cwd()`)
         *
         * @type {string}
         */
        this.base = dirname( path );

        /**
         * Whether include NPM modules in the final bundle
         *
         * @type {boolean}
         */
        this.includeAll = includeAll;

        /**
         * Module count of this package
         *
         * @type {number}
         */
        this.length = 0;

        /**
         * Reference count of modules in this package
         * (key for name & value for count)
         *
         * @type {Object}
         */
        this.module = { };

        /**
         * Key for original name of a module & value for module name of the replacement
         *
         * @type {Object}
         */
        this.moduleMap = moduleMap;

        /**
         * Whether show logs during the bundle process
         *
         * @type {boolean}
         */
        this.showLog = (! noLog);
    }

    /**
     * @param {Module|string} module - Instance or name of a module
     *
     * @return {number}
     */
    indexOf(module) {

        for (let i = 0;  this[i];  i++)
            if (
                (module instanceof Module)  ?
                    (module === this[i])  :  (module === this[i].name)
            )
                return i;

        return -1;
    }

    /**
     * @protected
     *
     * @param {string} modName - Path of a module
     *
     * @return {?Module} New module
     */
    register(modName) {

        const index = this.indexOf( modName );

        this.module[modName] = (this.module[modName] || 0)  +  1;

        if (index < 0) {

            Array_proto.unshift.call(
                this,
                new Module(modName, this.base, this.includeAll, this.moduleMap)
            );

            return this[0];
        }

        Array_proto.sort.call(this,  (A, B) => {

            if (B.dependencyPath.includes( A.name ))  return -1;

            if (A.dependencyPath.includes( B.name ))  return 1;

            return  this.module[ B.name ]  -  this.module[ A.name ];
        });
    }

    /**
     * Entry module of this package
     *
     * @type {Module}
     */
    get entry() {  return  this[this.length - 1];  }

    /**
     * @protected
     *
     * @param {string} modName - Path of a module
     */
    async parse(modName) {

        const module = this.register( modName );

        if (! module)  return;

        if ( this.showLog )
            module.on('replace',  (oldMod, newMod)  =>
                console.info(
                    `→ Module "${oldMod}" will be replaced by "${newMod}"`
                )
            );

        await module.parse();

        if ( this.showLog )
            console.info(`√ Module "${modName}" has been bundled`);

        await Promise.all(
            module.dependencyPath.map(path  =>  this.parse( path ))
        );
    }

    /**
     * Outside dependencies of this package
     *
     * @type {DependencyMap}
     */
    get outDependency() {

        return  this.includeAll  ?  [ ]  :  Object.assign(
            ... Array.from(this,  module => module.dependency.outside)
        );
    }

    /**
     * @protected
     *
     * @param {function(modName: string[], varName: string[]): string} bundler
     *
     * @return {string} Bundled source with UMD wrapper
     */
    wrap(bundler) {

        const outside = this.outDependency;

        const modName = Object.keys( outside ), varName = Object.values( outside );

        return `
//
//  Generated by https://www.npmjs.com/package/amd-bundle
//
(function (factory) {

    if ((typeof define === 'function')  &&  define.amd)
        define('${this.name}', ${JSON.stringify( modName )}, factory);
    else if (typeof module === 'object')
        return  module.exports = factory(${modName.map(name => `require('${name}')`)});
    else
        return  this.${this.name} = factory(${modName.map(name => `this.${name}`)});

})(${bundler(modName, varName)});`.trim();
    }

    /**
     * @return {string} Source code of this package
     */
    async bundle() {

        await this.parse(`./${this.name}`);

        return  this.wrap((modName, varName) => `function (${varName}) {

    var module = {
        ${Array.from(
        this,  item => `'${item.name}':  {exports: { }}`
    ).concat(
        modName.map((name, index)  =>  `'${name}':  {exports: ${varName[index]}}`)
    ).join(',\n        ')}
    };

${merge}

    function _require_(base, path) {

        return module[
            /^\\w/.test( path )  ?  path  :  ('./' + merge(base, path))
        ].exports;
    }

    var require = _require_.bind(null, './');

${Array.from(this,  item => item.source).join('\n\n')}

    ${Array.from(this,  item => `module['${item.name}'].exports = ${item.identifier}(${

        Object.keys( item.dependency.compile ).map(
            child => `require('${child}')`
        ).concat(
            `_require_.bind(null, '${item.base}')`,
            `require('${item.name}')`,
            `module['${item.name}']`
        ).join(', ')

    }) || require('${item.name}');`).join('\n\n    ')}

    return require('${this.entry.name}');
}`);
    }
}
